service:
  name: serverless-101

plugins:
  - serverless-offline

provider:
  name: aws
  region: eu-north-1
  runtime: nodejs12.x
  iamRoleStatements:
    # give our lambda access to S3
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - '*'
  apiGateway:
    binaryMediaTypes: # Allow the API to return any file type
      - '*/*'

package:
  individually: true

# define resources in a separate file
resources: ${file(cloudformation-resources.yml)}

functions:
  hello-world:
    handler: src/hello-world.handler
    events:
      - http:
          path: hello-world
          method: GET

  random-image:
    handler: src/random-image.handler
    events:
      - http:
          path: random-image
          method: GET
